services:
  fast_api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - .:/app
    command: /start
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.6
    restart: always
    hostname: mongo
    volumes:
      - ./config/database/datadir:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
